### ISSUE TITLE
Upgrade Mersenne Twister to SFMT/SMID for a better randomness generator

### ISSUE THREAD

**Issue by CodeLiftSleep** [CodeLiftSleep/Goal-Line-Stand-Football#32]
Need to update the C# implementation of this as it does not convert fully and has uses some things in VB2008 that are no longer supported in VB2015. Will replace the current Mersenne Twister implementation in Mersenne.dll

**Comment by RedfoxSoftware** [comment]
[SFMTInAction2.zip](https://github.com/CodeLiftSleep/Goal-Line-Stand-Football/files/174171/SFMTInAction2.zip)

upgraded to be compatible with VS 2015
