### ISSUE TITLE
Create Various Types of Coaches---DC,OC,ST, Position Coaches

### ISSUE THREAD

**Issue by CodeLiftSleep** [CodeLiftSleep/Goal-Line-Stand-Football#43]
Further Create various position coaches and coordinators

**Comment by wolfpac255** [comment]
-Head Coach
-Offensive Coordinator
-Defensive Coordinator
-Special Teams Coordinator
-Quarterbacks
-Running Backs
-Wide Receivers
-Tight Ends
-Defensive Line
-Linebackers
-Defensive Backs
-Strength and Conditioning

**Comment by CodeLiftSleep** [comment]
Completed
