### ISSUE TITLE
Create Trainers, Agents and other people missing

### ISSUE THREAD

**Issue by CodeLiftSleep** [CodeLiftSleep/Goal-Line-Stand-Football#44]
Need to finish creating other types of people associated with the game

**Comment by wolfpac255** [comment]
Coaching Staff
-Head Coach
-Offensive Coordinator
-Defensive Coordinator
-Special Teams Coordinator
-Quarterbacks
-Running Backs
-Wide Receivers
-Tight Ends
-Defensive Line
-Linebackers
-Defensive Backs
-Strength and Conditioning

Medical Staff
-Head Trainer
-Physical Therapist
-Team Physician
-Team Neurosurgeon

Other
-Director of Team Nutrition
-Head Groundskeeper
-Player Agent

**Comment by CodeLiftSleep** [comment]
Completed
