### ISSUE TITLE
Create Types of Scouts--Area Scouts, National Scout, etc

### ISSUE THREAD

**Issue by CodeLiftSleep** [CodeLiftSleep/Goal-Line-Stand-Football#46]
expand types of scouts

**Comment by wolfpac255** [comment]
Director of Player Personnel + Assistant
Director of Pro Personnel
-Pro Scout x2
Director of College Scouting
-College Scouting Coordinator
-Senior College Scout (National)
-College Scout (National)
-Area Scout x6 (Northeast/Southeast/Midwest/Central/Northwest/Southwest)

**Comment by CodeLiftSleep** [comment]
Completed
