### ISSUE TITLE
Create map of 6 regions for "Area Scouts" and assign colleges to each region

### ISSUE THREAD

**Issue by CodeLiftSleep** [CodeLiftSleep/Goal-Line-Stand-Football#52]
Determine the states that are included in each region and go through the college.txt file assigning colleges to each region based on location.

**Comment by wolfpac255** [comment]
[PlayersbyCollege.xlsx](https://github.com/CodeLiftSleep/Goal-Line-Stand-Football/files/189730/PlayersbyCollege.xlsx)

**Comment by CodeLiftSleep** [comment]
Very nice!
